config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  root to: 'posts#index'
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get :likes, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_category_relations, dependent: :destroy
  has_many :posts, through: :post_category_relations, dependent: :destroy

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :comments
  has_many :likes
  has_many :post_category_relations
  has_many :categories, through: :post_category_relations, dependent: :destroy

  # お気に入りされているか判定
  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search
      Post.where('text LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end

  validates :text, presence: true,length: { maximum: 200 }
  validates :image, presence: true
  validates :categories, presence: true

  mount_uploader :image, ImageUploader
end

app/models/post_category_relation.rb
class PostCategoryRelation < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  def self.guest
    find_or_create_by!(nickname:"ゲスト",email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  validates :profile, length: { maximum: 150 }
  validates :nickname, presence: true, length: { maximum: 6 }

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.create(comment_params)
    redirect_to "/posts/#{comment.post.id}"
  end

  def destroy
    Comment.find_by(id: params[:id],post_id: params[:post_id]).destroy
    redirect_to post_path(params[:post_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.build(post_id: params[:post_id])
    @like.save
    redirect_to "/posts/#{params[:post_id]}"
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_to "/posts/#{params[:post_id]}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @posts = Post.includes(:user).order("created_at Desc")
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to root_path
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  def edit
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to posts_path(post.id)
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def search
    @post = Post.search(params[:keyword]).order("created_at Desc")
  end

  private
  def post_params
    params.require(:post).permit(:image, :text, category_ids: [] ).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_to ("/users/#{params[:user_id]}")
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to ("/users/#{params[:user_id]}")
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :follows, :followers, :likes]
  # before_action :move_to_mypage, only: [:edit, :update]

  def show
    @posts = @user.posts.order("created_at Desc")

  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      redirect_to edit_user_path(current_user)
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def likes
    @like_posts = @user.like_posts.order("created_at Desc")
  end

  def user_params
    params.require(:user).permit(:nickname, :email, :image, :profile)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def move_to_mypage
    if @current_user != @user
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Room</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <header class="header">
      <div class="header__contents">
        <div class="header__contents--title">
          <%= link_to "Room", root_path, class: "header__contents--title--text"%>
        </div>
        <div class="header__contents--search">
          <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
          <div class="header__contents--center"><%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %></div>
          <%= form.submit "検索", class: "search-btn" %>
          <% end %>
        </div>

          <nav>
            <ul class="header__contents--left">
            <% if user_signed_in? %>
              <li><%= link_to  "新規投稿", "/posts/new", class: "header--post" %></li>
              <li><%= link_to current_user.nickname, user_path(current_user), class: "header--post"%></li>
              <% else %>
              <li><%= link_to "ログイン", new_user_session_path, class: 'header--post' %></li>
              <li><%= link_to "新規登録", new_user_registration_path, class: 'header--post' %></li>
              <% end %>
            </ul>
          </nav>
      </div>
    </header>

    <%= yield %>
    <%# <footer>
      <p>
        Copyright © 2020 Room, All Rights Reserved.
      </p>
    </footer> %>

  </body>
</html>

app/views/posts/_comment.html.erb
<div class="comments">
    <% if @comments %>
      <% @comments.each do |comment| %>
        <div class="comment">
          <% if @post.user.image? %>
            <%= image_tag(@post.user.image.to_s, size: '30x30' ,class: "user-icon")%>
            <% else %>
            <%= image_tag('icon.png', size: '30x30')%>
          <% end %>

          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}", class:'comment--user' %></strong>
          <%= comment.created_at.strftime('%Y/%m/%d %H:%M') %>
          <% if user_signed_in? && current_user.id == comment.user.id %>
          <%= link_to '削除する', post_comment_path(comment.post.id, comment.id), class: 'comment--delete', method: :delete %>
          <% end %>
          <div class="comment--text"><%= comment.text %></div>
        </div>
      <% end %>
    <% end %>

  <% if current_user %>
    <%= form_with(model: [@post, @comment], local: true) do |form| %>
      <%= form.text_area :text, placeholder: "コメントを入力して下さい(１５０文字以内）", rows: "3", class:'comment--text--box' %>
      <%= form.submit "コメントする", class:'submit-btn' %>
    <% end %>
    <% else %>
    <% end %>
</div>

app/views/posts/_post.html.erb
<div class="content_post" style="background-image: url(<%= post.image %>);">
      <div class="more">
          <ul class="more_list">
        　<li>
            <%= link_to '詳細', "/posts/#{post.id}", method: :get %>
          </li>
          <% if user_signed_in? && current_user.id == post.user_id %>
          <li>
            <%= link_to '編集', "/posts/#{post.id}/edit", method: :get %>
          </li>
            <li>
              <%= link_to '削除', "/posts/#{post.id}", method: :delete %>
            </li>
            <% end %>
          </ul>
      </div>
      <%= simple_format(post.text) %>
      <span class="name">
        <a href="/users/<%= post.user.id %>">
          <span>投稿者</span><%= post.user.nickname %>
        </a>
      </span>
    </div>

app/views/posts/edit.html.erb
<div class="contents row">
  <h3 class="contents-title">
    写真を編集する
  </h3>
  <div class="container">
    <div class="container__left">
      <div calss="pic-box">
        <div class="posts-title">写真を投稿する</div>
        <div class="required">※必須です</div>
        <div class="show-text">
          画像形式:JPEG/PNG
          <br>
          容量:5MB以内
        </div>
      </div>
      <div class='category-box'>
        <div class='posts-title'>カテゴリーを選択する</div >
        <div class= 'required'>※必須です</div>
        <div class='show-text'>1つだけ選択して下さい</div>
      </div>
      <div class='comment-box'>
        <div class='posts-title'>コメントを入力して下さい</div>
        <div class='required'>※必須です</div>
        <div class='show-text'>文字制限:200文字</div>
      </div>
    </div>
    <div class="container__right">
      <%= form_with(model: @post,local: true) do |form| %>
        <div class="image-box">
          <%= form.label :image, for: "file-input", class: "fa fa-camera fa-5x" do %>
          <%= form.file_field :image, id: "file-input", style: "display: none;" %>
          <% end %>
        </div>
        <div class="category-box-left">
          <%# ここにカテゴリー送信フォームを実装予定 %>
        </div>
        <div class="comment-text">
          <%= form.text_area :text, placeholder: "コメントを入力する" , size: "40x5", maxlength: "200", class: "comment-area" %>
        </div>
        <%= form.submit "写真を投稿する", class: "submit-btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="contents row">
  <div class="main-contents">
    <% @posts.each do |post| %>
      <div class="post-item">
        <div class="post-image">
          <%= link_to image_tag(post.image.to_s,size: '300x300'), post%>
        </div>
        <div class="post-nav">
          <% if post.user.image? %>
          <%= image_tag(post.user.image.to_s, size: '30x30' ,class: "user-icon")%>
          <% else %>
          <%= image_tag('icon.png', size: '30x30')%>
          <% end %>

          <%= link_to post.user.nickname, post.user, class: 'post-nav-user' %>
          <div class="post-nav-icon">
            <div><%= post.created_at.strftime('%Y/%m/%d %H:%M') %></div>
            <ul>
              <li class="fa fa-heart post-right" ><%= post.likes.count %></li>
              <li class="fa fa-comments post-right" ><%= post.comments.count %></li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="contents row">
  <h3 class="contents-title">
    写真を投稿する
  </h3>
  <div class="container">
    <div class="container__left">
      <div calss="pic-box">
        <div class="posts-title">写真を投稿する</div>
        <div class="required">※必須です</div>
        <div class="show-text">
          画像形式:JPEG/PNG
          <br>
          容量:5MB以内
        </div>
      </div>
      <div class='category-box'>
        <div class='posts-title'>カテゴリーを選択する</div >
        <div class= 'required'>※必須です</div>
        <div class='show-text'>該当するカテゴリーを選択下さい</div>
      </div>
      <div class='comment-box'>
        <div class='posts-title'>コメントを入力して下さい</div>
        <div class='required'>※必須です</div>
        <div class='show-text'>文字制限:200文字</div>
      </div>
    </div>
    <div class="container__right">
      <%= form_with(model: @post,local: true) do |form| %>
        <div class="image-box">
          <%= form.label :image, for: "file-input", class: "fa fa-camera fa-5x" do %>
          <%= form.file_field :image, id: "file-input", style: "display: none;" %>
          <% end %>
        </div>
        <div class="category-box-left">
          <%# ここにカテゴリー送信フォームを実装予定 %>
          <div class="category-box-left-text">
            <%= form.label :category,class:'category-label'%>
            <%= form.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %>
              <%= category.label do %>
                <%= category.check_box %>
                <%= category.text %>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="comment-text">
          <%= form.text_area :text, placeholder: "コメントを入力する" , size: "40x5", maxlength: "200", class: "comment-area" %>
        </div>
        <%= form.submit "写真を投稿する", class: "submit-btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<div class="contents row">
  <div class="main-contents">
    <% @post.each do |post| %>
      <div class="post-item">
        <div class="post-image">
          <%= link_to image_tag(post.image.to_s,size: '300x300'), post%>
        </div>
        <div class="post-nav">
          <% if post.user.image? %>
          <%= image_tag(post.user.image.to_s, size: '30x30' ,class: "user-icon")%>
          <% else %>
          <%= image_tag('icon.png', size: '30x30')%>
          <% end %>

          <%= link_to post.user.nickname, post.user, class: 'post-nav-user' %>
          <div class="post-nav-icon">
            <div><%= post.created_at.strftime('%Y/%m/%d %H:%M') %></div>
            <ul>
              <li class="fa fa-heart post-right" ><%= post.likes.count %></li>
              <li class="fa fa-comments post-right" ><%= post.comments.count %></li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class ="post__show">
  <div class="post__show__left">
    <div class="post__show__left--image"><%= image_tag(@post.image.to_s, size: '600x600') %></div>
    <div class="post__show__left--bottom">
      <div class="post__show__left--bottom--left">
        <%= @post.created_at.strftime('%Y/%m/%d %H:%M') %>
      </div>
      <div class="post__show__left--bottom--right">
        <% if user_signed_in? && current_user.id == @post.user_id %>
        |<%= link_to '削除', "/posts/#{@post.id}", method: :delete, class: "show-edit-btn" %>
        |<%= link_to '編集', "/posts/#{@post.id}/edit", method: :get, class: 'show-edit-btn' %>
        <% end %>
        <div>
          |<%= link_to 'シェア', "https://twitter.com/share?url=#{request.url}", title: 'Twitter', target: '_blank', class: 'show-edit-btn' %>|
        </div>
      </div>
    </div>
    <div class="post__show__left--text">
      <%= render 'posts/comment'%>
    </div>

  </div>
  <div class="post__show__right">
    <% if @post.user.image? %>
      <%= image_tag(@post.user.image.to_s, size: '80x80' ,class: "user-icon")%>
      <% else %>
      <%= image_tag('icon.png', size: '80x80')%>
      <% end %><br>
    <div class="post__show__right--user"><%= link_to @post.user.nickname, @post.user, class: 'user-nav' %></div>
    <div class='post__show__right__like'>
        <% if user_signed_in? %>
          <% if @post.liked_by?(current_user) %>
            <p><%= link_to 'いいね', post_like_path(@post.id), method: :delete, class: 'like-btn like' %></p>
            <% else %>
            <p><%= link_to 'いいね', post_likes_path(@post.id), method: :post, class: 'like-btn' %></p>
            <% end %>
          <% else %>
        <% end %>
    </div>
      <%= @post.likes.count %>人がいいねしています

    <div class="post__show__right__category">
      <div class="show-text">カテゴリー</div>
      <% @post.categories.each do |category| %>
      <span class="show-category"><%= category.name %></span>
      <% end %>
    </div>

      <div class="show-text">紹介文</div>
    <div class="post__show__right__text">
      <%= simple_format(@post.text) %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="mypage">
  <div class="mypage__left">
    <div class="mypage__left--top"><%= @user.nickname %>さんのフォロワー一覧</div>
    <hr>
    <% @users.each do |user| %>
      <% if user.image? %>
        <%= image_tag(user.image.to_s, size: '80x80' ,class: "user-icon")%>
      <% else %>
        <%= image_tag("icon.png", size: "80x80")%>
      <% end %>
      <%= link_to user.nickname, user_path(user.id), class: "follow-user" %>
      <hr>
      <% end %>
  </div>
  <div class="mypage__right">
    <div class="mypage__right__top">
      <div class="mypage__right__top--icon">
      <% if @user.image? %>
      <%= image_tag(@user.image.to_s, size: '80x80' ,class: "user-icon")%>
      <% else %>
      <%= image_tag('icon.png', size: '80x80')%>
      <% end %>
      </div>
      <div class="mypage__right__top--name">
        <span><%= @user.nickname %></span>
      </div>
      <div class="mypage__right__top--tag">
      </div>
      <div class="mypage__right__top--edit">
        <% if user_signed_in? %>
          <% if current_user.id == @user.id%>
            <div class="link-btn"><%= link_to 'プロフィールを編集する', edit_user_path(current_user), class: 'profile-edit' %></div>
            <% else%>
              <% if @user.followed_by?(current_user) %>
                <p><%= link_to "フォロー中", user_relationships_path(@user.id), method: :delete,class: 'profile-edit now' %></p>
              <% else %>
                <p><%= link_to "フォローする", user_relationships_path(@user.id), method: :post,class: 'profile-edit' %></p>
              <% end %>
            <% end %>
          <% else %>
          <%# 非表示 %>
        <% end %>
      </div>
      <div class="mypage__right__top--link">
        <ul>
          <li class="btn-list">   <%= link_to "フォロー", follows_user_path(@user.id), class: "link"%>
          <li class="btn-list">   <%= link_to "フォロワー",followers_user_path(@user.id), class: "link"%>
          <li class="btn-list">   <%= link_to "いいねした投稿",likes_user_path(@user.id), class: "link"%>
          <% if user_signed_in? && current_user.id == @user.id%>
            <li class="btn-list">   <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "link" %>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="mypage__right__text">
      <div class="mypage__right--profile">自己紹介</div>
      <%= simple_format(@user.profile) %>
    </div>
  </div>
</div>

app/views/users/follows.html.erb
<div class="mypage">
  <div class="mypage__left">
    <div class="mypage__left--top"><%= @user.nickname %>さんのフォロー一覧</div>
    <hr>
    <% @users.each do |user| %>
      <% if user.image? %>
        <%= image_tag(user.image.to_s, size: '80x80' ,class: "user-icon")%>
      <% else %>
          <%= image_tag("icon.png", size: "80x80")%>
      <% end %>
      <%= link_to user.nickname, user_path(user.id), class: "follow-user" %>
      <hr>
      <% end %>
  </div>
  <div class="mypage__right">
    <div class="mypage__right__top">
      <div class="mypage__right__top--icon">
      <% if @user.image? %>
      <%= image_tag(@user.image.to_s, size: '80x80' ,class: "user-icon")%>
      <% else %>
      <%= image_tag('icon.png', size: '80x80')%>
      <% end %>
      </div>
      <div class="mypage__right__top--name">
        <span><%= @user.nickname %></span>
      </div>
      <div class="mypage__right__top--tag">
      </div>
      <div class="mypage__right__top--edit">
        <% if user_signed_in? %>
          <% if current_user.id == @user.id%>
            <div class="link-btn"><%= link_to 'プロフィールを編集する', edit_user_path(current_user), class: 'profile-edit' %></div>
            <% else%>
              <% if @user.followed_by?(current_user) %>
                <p><%= link_to "フォロー中", user_relationships_path(@user.id), method: :delete,class: 'profile-edit now' %></p>
              <% else %>
                <p><%= link_to "フォローする", user_relationships_path(@user.id), method: :post,class: 'profile-edit' %></p>
              <% end %>
            <% end %>
          <% else %>
          <%# 非表示 %>
        <% end %>
      </div>
      <div class="mypage__right__top--link">
        <ul>
          <li class="btn-list">   <%= link_to "フォロー", follows_user_path(@user.id), class: "link"%>
          <li class="btn-list">   <%= link_to "フォロワー",followers_user_path(@user.id), class: "link"%>
          <li class="btn-list">   <%= link_to "いいねした投稿",likes_user_path(@user.id), class: "link"%>
          <% if user_signed_in? && current_user.id == @user.id%>
            <li class="btn-list">   <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "link" %>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="mypage__right__text">
      <div class="mypage__right--profile">自己紹介</div>
      <%= simple_format(@user.profile) %>
    </div>
  </div>
</div>

app/views/users/likes.html.erb
<div class="mypage">
  <div class="mypage__left">
    <div class="mypage__left--top"><%= @user.nickname %>さんがいいねした投稿</div>
    <% @like_posts.each do |post| %>
    <%= link_to image_tag(post.image.to_s,size: '200x230'), post%>
    <% end %>
  </div>
  <div class="mypage__right">
    <div class="mypage__right__top">
      <div class="mypage__right__top--icon">
      <% if @user.image? %>
      <%= image_tag(@user.image.to_s, size: '80x80' ,class: "user-icon")%>
      <% else %>
      <%= image_tag('icon.png', size: '80x80')%>
      <% end %>
      </div>
      <div class="mypage__right__top--name">
        <span><%= @user.nickname %></span>
      </div>
      <div class="mypage__right__top--tag">
      </div>
      <div class="mypage__right__top--edit">
        <% if user_signed_in? %>
          <% if current_user.id == @user.id%>
            <div class="link-btn"><%= link_to 'プロフィールを編集する', edit_user_path(current_user), class: 'profile-edit' %></div>
            <% else%>
              <% if @user.followed_by?(current_user) %>
                <p><%= link_to "フォロー中", user_relationships_path(@user.id), method: :delete,class: 'profile-edit now' %></p>
              <% else %>
                <p><%= link_to "フォローする", user_relationships_path(@user.id), method: :post,class: 'profile-edit' %></p>
              <% end %>
            <% end %>
          <% else %>
          <%# 非表示 %>
        <% end %>
      </div>
      <div class="mypage__right__top--link">
        <ul>
          <li class="btn-list">   <%= link_to "フォロー", follows_user_path(@user.id), class: "link"%>
          <li class="btn-list">   <%= link_to "フォロワー",followers_user_path(@user.id), class: "link"%>
          <li class="btn-list">   <%= link_to "いいねした投稿",'#', class: "link"%>
          <% if user_signed_in? && current_user.id == @user.id%>
            <li class="btn-list">   <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "link" %>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="mypage__right__text">
      <div class="mypage__right--profile">自己紹介</div>
      <%= simple_format(@user.profile) %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="mypage">
  <div class="mypage__left">
    <div class="mypage__left--top">
      <div><%=@user.nickname%>さんの投稿一覧</div>

    </div>
    <div class="mypage__left--content">
      <% @posts.each do |post| %>
        <%= link_to image_tag(post.image.to_s,size: '200x230'), post%>
      <% end %>
    </div>
  </div>
  <div class="mypage__right">
    <div class="mypage__right__top">
      <div class="mypage__right__top--icon">
      <% if @user.image? %>
      <%= image_tag(@user.image.to_s, size: '80x80' ,class: "user-icon")%>
      <% else %>
      <%= image_tag('icon.png', size: '80x80')%>
      <% end %>
      </div>
      <div class="mypage__right__top--name">
        <span><%= @user.nickname %></span>
      </div>
      <div class="mypage__right__top--tag">
      </div>
      <div class="mypage__right__top--edit">
        <% if user_signed_in? %>
          <% if current_user.id == @user.id%>
            <div class="link-btn"><%= link_to 'プロフィールを編集する', edit_user_path(current_user), class: 'profile-edit' %></div>
            <% else%>
              <% if @user.followed_by?(current_user) %>
                <p><%= link_to "フォロー中", user_relationships_path(@user.id), method: :delete,class: 'profile-edit now' %></p>
              <% else %>
                <p><%= link_to "フォローする", user_relationships_path(@user.id), method: :post,class: 'profile-edit' %></p>
              <% end %>
            <% end %>
          <% else %>
          <%# 非表示 %>
        <% end %>
      </div>
      <div class="mypage__right__top--link">
        <ul>
          <li class="btn-list">   <%= link_to "フォロー", follows_user_path(@user.id), class: "link"%>
          <li class="btn-list">   <%= link_to "フォロワー",followers_user_path(@user.id), class: "link"%>
          <li class="btn-list">   <%= link_to "いいねした投稿",likes_user_path(@user.id), class: "link"%>
          <% if user_signed_in? && current_user.id == @user.id%>
            <li class="btn-list">   <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "link" %>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="mypage__right__text">
      <div class="mypage__right--profile">自己紹介</div>
      <%= simple_format(@user.profile) %>
    </div>
  </div>
</div>